// Copyright 2026 AIVory, Inc.
// SPDX-License-Identifier: Apache-2.0
// Vendor the chart-engine bundles as base64 TS string modules. They then ship via
// normal `tsc` (no runtime fs read, no npm *runtime* dependency) and can be inlined
// lazily into a deck's HTML. Re-run after bumping a pinned version below.
//
// We store base64 (not raw JS) so the bundle is safe both inside a TS string literal
// (no backtick / `${` collisions) and inside an inert `<script type="text/plain">` tag
// (no stray `</script>`). The boot loader decodes + evals it on first chart render.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const renderDir = join(here, '..', '..', 'src', 'render');

interface Lib {
  name: string;
  global: string;
  version: string;
  url: string;
  out: string;
  constName: string;
  license: string;
}

const LIBS: Lib[] = [
  {
    name: 'mermaid',
    global: 'mermaid',
    version: '10.9.3',
    url: 'https://cdn.jsdelivr.net/npm/mermaid@10.9.3/dist/mermaid.min.js',
    out: 'mermaid-lib.generated.ts',
    constName: 'MERMAID_LIB_B64',
    license: 'MIT — mermaid-js/mermaid',
  },
  {
    name: 'echarts',
    global: 'echarts',
    version: '5.5.1',
    url: 'https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js',
    out: 'echarts-lib.generated.ts',
    constName: 'ECHART_LIB_B64',
    license: 'Apache-2.0 — apache/echarts',
  },
];

for (const lib of LIBS) {
  console.log(`Fetching ${lib.name}@${lib.version} …`);
  const res = await fetch(lib.url);
  if (!res.ok) throw new Error(`${lib.name}: HTTP ${res.status} from ${lib.url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const b64 = buf.toString('base64');
  const ts =
    `// Copyright 2026 AIVory, Inc.\n` +
    `// SPDX-License-Identifier: Apache-2.0\n` +
    `// GENERATED by scripts/dev/vendor-charts.ts — do not edit by hand.\n` +
    `// Vendored ${lib.name}@${lib.version} (${lib.license}).\n` +
    `// Base64 of the UMD min bundle; eval'd at global scope it defines window.${lib.global}.\n` +
    `export const ${lib.constName} =\n  '${b64}';\n`;
  writeFileSync(join(renderDir, lib.out), ts, 'utf8');
  console.log(
    `  → src/render/${lib.out}  (${(buf.length / 1024).toFixed(0)} KB raw → ${(b64.length / 1024).toFixed(0)} KB base64)`,
  );
}
console.log('Done. Remember: these bundles are third-party — see THIRD-PARTY.md.');
